# copy right
# Licenses http://www.apache.org/licenses/LICENSE-2.0
# more info see https://docs.docker.com/compose/compose-file/ or https://docker.github.io/compose/compose-file/
version: '3.7'

networks:
  default:
#volumes:
#  web-data:
services:
  example-temp-gin:
    container_name: "${ROOT_NAME}"
    image: '${ROOT_NAME}:${DIST_TAG}' # see local docker file
    ports:
      - "39000:${ENV_WEB_PORT}"
    volumes:
      - "$PWD:/usr/src/myapp"
    environment:
      - ENV_WEB_HTTPS_ENABLE=false
      - ENV_WEB_AUTO_HOST=false
      - ENV_WEB_HOST=${ENV_WEB_HOST}:${ENV_WEB_PORT}
#      - ENV_WEB_HOST=0.0.0.0:39000
    working_dir: "/usr/src/myapp"
    command: ["make", "${ENV_MAKE_TASK}"]
